import re

import httpx
from fastapi import HTTPException
from sqlalchemy.orm import Session

from app.config.settings import settings
from app.models.task import Task
from app.schemas.task import TaskCreate, TaskUpdate

WIKI_API_URL = "https://en.wikipedia.org/w/api.php"


# ---------- Database CRUD (normal sync functions) ----------

def get_tasks(db: Session, page: int, limit: int) -> list[Task]:
    # Pagination: page 1 skips 0 rows, page 2 skips `limit` rows, etc.
    offset = (page - 1) * limit
    return db.query(Task).order_by(Task.id).offset(offset).limit(limit).all()


def get_task(db: Session, task_id: int) -> Task:
    task = db.query(Task).filter(Task.id == task_id).first()
    if task is None:
        # HTTPException stops the function and FastAPI turns it into
        # an HTTP error response with this status code and JSON detail.
        raise HTTPException(status_code=404, detail="Task not found")
    return task


def create_task(db: Session, data: TaskCreate) -> Task:
    # model_dump() turns the Pydantic object into a dict;
    # ** unpacks it into keyword arguments for the SQLAlchemy model.
    task = Task(**data.model_dump())
    db.add(task)       # stage the new row in the session
    db.commit()        # actually write it to the database
    db.refresh(task)   # reload so task.id (generated by the DB) is filled in
    return task


def update_task(db: Session, task_id: int, data: TaskUpdate) -> Task:
    task = get_task(db, task_id)  # reuses the 404 logic
    for field, value in data.model_dump().items():
        setattr(task, field, value)
    db.commit()
    db.refresh(task)
    return task


def delete_task(db: Session, task_id: int) -> None:
    task = get_task(db, task_id)
    db.delete(task)
    db.commit()


# ---------- External API (async function) ----------

async def get_external_info(db: Session, task_id: int) -> dict:
    task = get_task(db, task_id)

    if not task.topic:
        # 400 = the client's request can't be satisfied as sent
        raise HTTPException(status_code=400, detail="Task has no topic to look up")

    # params become the query string: ...api.php?action=query&list=search&...
    params = {
        "action": "query",
        "list": "search",
        "srsearch": task.topic,
        "srlimit": 1,
        "format": "json",
    }
    # Wikimedia asks every client to identify itself with a User-Agent header.
    # This is the only header needed; no authentication is required.
    headers = {"User-Agent": settings.wiki_user_agent}

    try:
        # AsyncClient + await: while waiting for Wikipedia's network response,
        # FastAPI can serve other requests instead of sitting idle.
        # timeout: give up if Wikipedia takes too long, so we never hang forever.
        async with httpx.AsyncClient(timeout=settings.external_api_timeout) as client:
            response = await client.get(WIKI_API_URL, params=params, headers=headers)

            # status_code is just a number; nothing happens automatically.
            # Use it when you want to handle a SPECIFIC status yourself.
            if response.status_code == 429:
                raise HTTPException(
                    status_code=503,
                    detail="Wikipedia is rate limiting us, try again later",
                )

            # raise_for_status() is the catch-all: it raises
            # httpx.HTTPStatusError for ANY 4xx/5xx response,
            # so you don't need to check each code manually.
            response.raise_for_status()

    except httpx.TimeoutException:
        # Must come BEFORE RequestError (it is a more specific subclass)
        raise HTTPException(status_code=504, detail="Wikipedia timed out")
    except httpx.HTTPStatusError as exc:
        # The external service answered, but with an error.
        # 502 Bad Gateway = "our backend depends on another service that failed".
        raise HTTPException(
            status_code=502,
            detail=f"Wikipedia returned status {exc.response.status_code}",
        )
    except httpx.RequestError:
        # Network-level failure: DNS problem, connection refused, etc.
        raise HTTPException(status_code=502, detail="Could not reach Wikipedia")

    # Parse JSON only after we know the request succeeded
    results = response.json()["query"]["search"]
    if not results:
        raise HTTPException(
            status_code=404,
            detail=f"No Wikipedia article found for '{task.topic}'",
        )

    best = results[0]
    # Wikipedia's snippet contains HTML tags like <span>; strip them
    snippet = re.sub(r"<[^>]+>", "", best["snippet"])

    # Returned as a dict; the router's response_model validates its shape
    return {
        "task_id": task.id,
        "topic": task.topic,
        "wikipedia_title": best["title"],
        "snippet": snippet,
        "url": "https://en.wikipedia.org/wiki/" + best["title"].replace(" ", "_"),
    }